const errorMessageConstants = {
    users: {
        profile: "User profile details not found",
        login: "Invalid login credentials",
        register: "User already exists",
        verifyOtp: "Invalid OTP",
        otp: "Send OTP failed",
        logout: "Logout failed",
        verifySession: "Session verification failed",
        forgotPassword: "Forgot password failed",
        accountDeactivated: "Account deactivated",
        invalidToken: "Invalid token",
        invalidCollaboratorEmail: "Invalid collaborator email",
        invalidCollaboratorPassword: "Invalid collaborator password",
        collaboratorNotFound: "Collaborator not found",
        collaboratorPasswordNotAssociatedWithGoogle: "Collaborator password not associated with Google",
        invalidPasswordResetToken: "Invalid password reset token",
        invalidOTP: "Invalid OTP",
        invalidCollaboratorData: "Invalid collaborator data",
        collaboratorEmailAlreadyExists: "Collaborator email already exists",
    },
    products: {
        productNotFound: "Product not found",
        failedToFetchProducts: "Failed to fetch products",
        failedToFetchProduct: "Failed to fetch product",
        failedToCreateProduct: "Failed to create product",
        invalidProductData: "Invalid product data",
        failedToUpdateProduct: "Failed to update product",
        failedToDeleteProduct: "Failed to delete product",
        productAlreadyExists: "Product already exists",
        failedToAssignProductToStudent: "Failed to assign product to student",
        tagsNotProvided: "Tags not provided",
        invalidCSVFile: "Invalid CSV file",
        errorOccurred: "Error occurred",
        failedToCompleteProductAssignment: "Failed to complete product assignment",
        emailTemplateNotFound: "Email template not found",
        failedToCheckStudentDetails: "Failed to check student details",
    },
    billing: {
        planNotFound: "Plan not found",
        failedToFetchPlans: "Failed to fetch plans",
        failedToFetchActivePlan: "Failed to fetch active plan",
        failedToSelectPlan: "Failed to select plan",
        noPlanSelected: "No plan selected",
        failedToCalculateAmount: "Failed to calculate payment amount",
        failedToCreateOrder: "Failed to create payment order",
        failedToVerifyPayment: "Failed to verify payment",
        invalidPaymentSignature: "Invalid payment signature",
        paymentNotFound: "Payment not found",
    },
};

export default errorMessageConstants;
