name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: YOUR_PROJECT_ID

    - name: Configure Docker for gcloud
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          --tag gcr.io/YOUR_PROJECT_ID/YOUR_SERVICE_NAME:$GITHUB_SHA \
          --push .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy YOUR_SERVICE_NAME \
          --image gcr.io/YOUR_PROJECT_ID/YOUR_SERVICE_NAME:$GITHUB_SHA \
          --region YOUR_REGION \
          --platform managed \
          --allow-unauthenticated
